# Generated by Django 2.0.7 on 2018-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledefornecedores', '0003_controle_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='tipo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default=123, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='CNPJ',
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True, verbose_name='CNPJ'),
        ),
    ]
