# Generated by Django 2.0.7 on 2018-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledefornecedores', '0005_auto_20180810_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='CNPJ',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CNpj'),
        ),
    ]
