# Generated by Django 2.0.7 on 2018-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controledefornecedores', '0007_auto_20180810_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], verbose_name='Tipo'),
        ),
    ]
